name: publish to dockerhub

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '**'

jobs:
  build:
    name: publish to dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: prepare
        id: prepare
        run: |
            TAG=${GITHUB_REF#refs/tags/}
            echo ::set-output name=tag_name::${TAG}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build (and publish) LIGHT docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            fopina/torproxy:light
            fopina/torproxy:light-${{ steps.prepare.outputs.tag_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            VERSION=${{ steps.prepare.outputs.tag_name }}
            BASE=alpine:3.13
          target: lightversion

      - name: build (and publish) FULL docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            fopina/torproxy:latest
            fopina/torproxy:${{ steps.prepare.outputs.tag_name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            VERSION=${{ steps.prepare.outputs.tag_name }}
            BASE=python:3.9-alpine3.13
